version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    # networks:
    #   - app-network
  # app:
  #   container_name: note-taking-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=5000
  #     - JWT_SECRET=your_jwt_secret
  #     - JWT_EXPIRES_IN=1h
  #     - MONGO_URI=mongodb://mongo:27017/note-taking-dev
  #   volumes:
  #     - ./:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - mongo
  #   networks:
  #     - app-network

volumes:
  mongo-data:

# networks:
#   app-network:
#     driver: bridge
